- name: FPM | Install base fpm package module
  ansible.builtin.package:
    name: "{{ php_fpm_prefix }}-fpm"
    state: present
  become: true
  tags:
    - phpfpm

- name: FPM | Patch default settings /etc/php/8.0/fpm/pool.d/www.conf
  ansible.builtin.lineinfile:
    dest: /etc/php/8.0/fpm/pool.d/www.conf
    regexp: "{{ item.regexp }}"
    line: "{{ item.line }}"
    insertafter: "{{ item.insertafter | default('EOF') }}"
  with_items: "{{ default_pool_properties | default([]) }}"
  become: true
  tags:
    - phpfpm

- name: FPM | Patch custom settings /etc/php/8.0/fpm/pool.d/www.conf
  ansible.builtin.lineinfile:
    dest: /etc/php/8.0/fpm/pool.d/www.conf
    regexp: "{{ item.regexp }}"
    line: "{{ item.line }}"
    insertafter: "{{ item.insertafter | default('EOF') }}"
  with_items: "{{ custom_pool_properties | default([]) }}"
  become: true
  tags:
    - phpfpm

- name: FPM | Stop fpm service if custom pool properties exist
  ansible.builtin.service:
    name: "php8.0-fpm"
    state: stopped
  when: custom_pool_properties is defined
  become: true
  tags:
    - phpfpm

- name: FPM | Restart fpm service
  ansible.builtin.service:
    name: "php8.0-fpm"
    state: restarted
  when: docker_test is not defined
  become: true
  tags:
    - phpfpm
